/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.ocsoft.nodejs

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.NamedDomainObjectFactory

/**
 * A simple 'hello world' plugin.
 */
public class Plugin implements org.gradle.api.Plugin<Project> {

    private final static String CLI_PREFIX = "nodeCli"
    public void apply(Project project) {
        def settings = new Settings()
        project.extensions.add("nodejsSettings", settings)
        def cliSettings = project.container(CliSetting.class,
            new NamedDomainObjectFactory<CliSetting>() {
                public CliSetting create(String name) {
                    return new CliSetting(name)
                }
            })
        project.extensions.add("nodejsCliSettings", cliSettings)
         
        project.tasks.addRule(
            "${CLI_PREFIX}_<Module>_<Command>_<Id> Run node cli") {
            def prefix = "${CLI_PREFIX}_"
            def pos = it.indexOf(CLI_PREFIX) 
            def taskName = it
            if (pos == 0) {
                def moduleCommandName = it.substring(prefix.length()) 
                def elems  = moduleCommandName.split("_")

                def moduleCommand
                if (elems.length > 1) {
                    moduleCommand = [
                        elems[0],
                        elems[1]
                    ]
                } else {
                    moduleCommand = [
                        elems[0], 
                        elems[0]
                    ]
                }

                def task = project.tasks.findByPath(taskName) 
                if (task == null) {
                    def exec = CliTask.resolveExec(
                        moduleCommand[0], moduleCommand[1], 
                        project)
                    if (exec != null) {
                        project.tasks.create(taskName, CliTask) {
                            executable = exec
                        } 
                    }
                }
            }
        }
    }
}
// vi: se ts=4 sw=4 et:
