/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.ocsoft.nodejs

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A functional test for the 'net.ocsoft.nodejs' plugin.
 */
public class PluginNpmFunctionalTest2 extends Specification {
    def "can npm install"() {
        given:
        def projectDir = new File("build/functionalTest/npm-run-2")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle").text = ""
        new File(projectDir, "build.gradle").text = """
plugins {
    id('net.ocsoft.nodejs')
}

tasks.npm_install.configure {
    workingDir = projectDir
    command = 'install'
    dependsOn tasks.nodejsModules
}

task npmTest {
    dependsOn npm_install
}
"""
        new File(projectDir, "package.json").text = '''
{
    "name": "npm-run-2",
    "dependencies": {
        "yaml" : "^1.10.0"
    }
}
'''

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("npmTest")
        runner.withProjectDir(projectDir)
        runner.build()

        then:
        def packageLock = new File(projectDir, "package-lock.json").text 
        
        packageLock.contains("yaml")
    }
}
// vi: se ts=4 sw=4 et:
