/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.ocsoft.nodejs

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * Plugin setting test
 */
public class SettingFunctionalTest extends Specification {
    def "specifing directory"() {
        given:
        def projectDir = new File("build/functionalTest/specifing-directory")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle").text = ""
        new File(projectDir, "build.gradle").text = """
plugins {
    id('net.ocsoft.nodejs')
}

nodejsSettings {
    installNodeModules = true
    moduleDirectory = buildDir
}

tasks.nodejsModules.configure {
    doFirst {
        mkdir buildDir
    }
    install 'yaml'
}

task installNpm {
    dependsOn tasks.nodejsModules
}

"""
        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("installNpm")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        def nodeModuleDir = new File(
            new File(projectDir, 'build'), 'node_modules')

        nodeModuleDir.directory
    }
}
// vi: se ts=4 sw=4 et:
