/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.ocsoft.nodejs

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'gradle.nodejs.greeting' plugin.
 */
public class PluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("net.ocsoft.nodejs")
        project.extensions.configure("nodejsSettings") {
           it.installNodeModules = true 
        }
        then:
        project.tasks.findByName("nodeCli_less_lessc") != null
    }


}
// vi: se ts=4 sw=4 et:
